### ISSUE TITLE
Trouble with `tempfile`

### ISSUE THREAD

**Issue by MauroMardones** [pepijn-devries/CopernicusMarine#37]
i don't know but i cant find temp files
im trying to reproduce the example but doesn't work.

```
destination <- tempfile("copernicus",
                         fileext = ".nc")
 cms_download_subset(
   destination   = destination,
   product       = "GLOBAL_ANALYSISFORECAST_PHY_001_024",
   layer         = "cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m",
   variable      = "sea_water_velocity",
   region        = c(-1, 50, 10, 55),
   timerange     = c("2021-01-01", "2021-01-02"),
   verticalrange = c(0, 2)
 )
```
Preparing job...
Waiting for job to finish...
Downloading file...
Done

``` 
mydata <- stars::read_stars(destination)
```

trying to read file: /private/var/folders/gy/29v3nsg15sq1rrxs23t_rt_m0000gn/T/RtmpHvp0jC/copernicus94ab42c83d89.nc
Error: file not found

**Comment by pepijn-devries** [comment]
Hi @MauroMardones,

Thank you for your feedback. I cannot reproduce your issue. Could your create a reprex using the [reprex](https://github.com/tidyverse/reprex) package and provide `sessionInfo()`? What happens when you download to a specific file location (i.e., not a temporary file)? Can you get a file listing for this path: `/private/var/folders/gy/29v3nsg15sq1rrxs23t_rt_m0000gn/T/RtmpHvp0jC/`?

**Comment by pepijn-devries** [comment]
Due to lack of activity and reproducibility, I'm closing this issue
