### ISSUE TITLE
cms_products_list() -  A tibble: 0 × 0

### ISSUE THREAD

**Issue by ValentinTeillard** [pepijn-devries/CopernicusMarine#43]
Hello, 

I'm trying to get the different products with cms_products_list()
But the result is always :
# A tibble : 0 × 0

I tried to connect thinking this was the problem and I connected perfectly but the result is still the same.

Thank you for your attention.

**Comment by pepijn-devries** [comment]
Hi @ValentinTeillard,

Thanks for reporting. Apparently, Copernicus had changed their remote API that was called by this function. This is fixed in https://github.com/pepijn-devries/CopernicusMarine/pull/44/commits/ea6f8aeac71c5f2d5a141a1bad5bb038a34be27b

Your problem should be solved by installing the developmental version of the package >= v0.2.3.002

**Comment by ValentinTeillard** [comment]
Thank you, problem solved :)
